version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: keepassdb
      POSTGRES_USER: keepassuser
      POSTGRES_PASSWORD: keepasspass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keepassuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      PGHOST: db
      PGUSER: keepassuser
      PGPASSWORD: keepasspass
      PGDATABASE: keepassdb
      PGPORT: 5432
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pg_data: